# version format
version: 0.1.{build}

environment:
  access_token:
    secure: eWAovbJD8C/F5ObWegnOimwNFyeU1vXzW6lwbJzhHpSUgjT+CMexMcPUBMKrm+Wl
  psgallery_key:
    secure: FuPgJskczZMptxRgdUlBAy7OYmXBQl4zq86kXXSmBt6wKudnM2PK7W6cM7bj0te1
  coveralls_key:
    secure: lCe6CMSzOCxMfS6HrSP0Emt/0+ESY+ysqF6Y1PB4wh2PII2G7PtNARzFH+tRXwLs

skip_commits:
  files:
    - .github\*
    - .vscode\*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
    - appveyor.yml
  message: /update readme.*|update version.*|update appveyor.*/

only_commits:
  files:
    - VaultControl\
    - Tests\

os: WMF 5

install:
  - ps: . .\build\install.ps1

build_script:
  - ps: . .\build\build.ps1

test_script:
  - ps: . .\build\test.ps1

deploy_script:
  - ps: . .\build\deploy.ps1